SELECT FOOD_TYPE, REST_ID, REST_NAME,FAVORITES
FROM(SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
           MAX(FAVORITES) OVER (PARTITION BY FOOD_TYPE) AS MAX_FAV
FROM REST_INFO)
WHERE FAVORITES = MAX_FAV
ORDER BY FOOD_TYPE DESC


