-- 코드를 입력하세요
SELECT MEMBER_ID,MEMBER_NAME,GENDER, SUBSTR(STR_TO_DATE(DATE_OF_BIRTH, '%Y-%m-%d'),1,10) AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE SUBSTR(DATE_OF_BIRTH,6,2)='03'
      AND GENDER='W'
      AND TLNO is not null